apiVersion: 1

datasources:
  - name: PostgreSQL-Warehouse
    type: postgres
    url: warehouse-postgres:5432
    database: warehouse
    user: warehouse
    secureJsonData:
      password: warehouse123
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
